// src/components/MarkdownPreview.jsx
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm'; // For GitHub Flavored Markdown (tables, etc.)

function MarkdownPreview({ content }) {
  if (!content) {
    // This case should ideally be handled by the parent (App.js)
    // by not rendering MarkdownPreview or showing a placeholder there.
    // However, adding a fallback here is safe.
    return (
      <div className="p-4 text-slate-500 text-center">
        La vista previa aparecerá aquí...
      </div>
    );
  }

  return (
    // The parent div in App.js already has:
    // className="prose prose-sm sm:prose lg:prose-base max-w-none flex-grow overflow-y-auto p-1 border border-slate-200 rounded-md bg-slate-50 custom-scrollbar"
    // So, MarkdownPreview itself doesn't need much styling wrapper here.
    // The 'prose' class from Tailwind Typography will style the HTML elements generated by ReactMarkdown.
    <ReactMarkdown remarkPlugins={[remarkGfm]}>
      {content}
    </ReactMarkdown>
  );
}

export default MarkdownPreview;